{% set name = "aom" %}
{% set version = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://storage.googleapis.com/aom-releases/libaom-{{ version }}.tar.gz
  sha256: 9e9775180dec7dfd61a79e00bda3809d43891aee6b2e331ff7f26986207ea22e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - perl
    - nasm      # [not (osx and arm64)]
    # we need binutils for the `as` executable
    - binutils  # [aarch64]
    - make      # [unix]
test:
  commands:
    - aomenc --help  # [build_platform == target_platform]
    - aomdec --help  # [build_platform == target_platform]
    - test -f ${PREFIX}/include/aom/aom.h            # [unix]
    - test -f ${PREFIX}/lib/libaom${SHLIB_EXT}       # [unix]
    - test ! -f ${PREFIX}/lib/libaom.a               # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/aom.pc         # [unix]
    - if not exist %LIBRARY_INC%\\aom\\aom.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\aom.dll exit 1     # [win]

about:
  home: https://aomedia.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Alliance for Open Media video codec
  description: |
    AOMedia Video 1 (AV1), is an open, royalty-free video coding format designed for
    video transmissions over the Internet.
  dev_url: https://aomedia.googlesource.com/aom/
  doc_url: https://aomedia.googlesource.com/aom/
extra:
  recipe-maintainers:
    - matthiasdiener
